language: cpp
compiler:
    - gcc
notifications:
    email: false
env:
    matrix: 
        - PKGADD="Cbc;Clp" JULIAVERSION="julianightlies" 
        - PKGADD="Cbc;Clp" JULIAVERSION="juliareleases" 
        - PKGADD="GLPKMathProgInterface" JULIAVERSION="julianightlies" 
        - PKGADD="GLPKMathProgInterface" JULIAVERSION="juliareleases" 
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install julia -y
    - sudo apt-get install libgmp-dev -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'versioninfo(); Pkg.init();'
    - julia -e 'for p in split(ENV["PKGADD"],";") Pkg.add(p) end'
    - mkdir -p ~/.julia/JuMP
    - cp -R ./* ~/.julia/JuMP/
    - cd ~/.julia/JuMP/
    - julia test/runtests.jl
    - julia test/hygiene.jl
