language: julia
os:
    - linux
#   - osx # Disable to speed up CI. JuMP has no binary dependency so the result
          # with osx and linux should be similar.
julia:
    - 0.7
    - 1.0
# This is left as an example for the next big version switch.
# matrix:
#     allow_failures:
#         - julia: 0.7
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
after_success:
    - julia -e '(VERSION >= v"0.7" && using Pkg); Pkg.add("Coverage"); cd(Pkg.dir("JuMP")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
    - stage: "Examples"
      julia: 1.0
      os: linux
      script:
        - julia --project=examples -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=examples --color=yes examples/run_examples.jl
