language: cpp
compiler:
    - gcc
os:
    - linux
    - osx
notifications:
    email: false
env:
    matrix: 
        - PKGADD="FactCheck;Cbc;Clp;GLPKMathProgInterface;Ipopt" JULIAVERSION="juliareleases"
        - PKGADD="FactCheck;GLPKMathProgInterface" JULIAVERSION="julianightlies" 
before_install:
    - curl http://julialang.org/install-julia.sh | sh -s $JULIAVERSION
    - if [ `uname` = "Linux" ]; then
        sudo apt-get install gfortran liblapack-dev libgmp-dev libglpk-dev;
      fi
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'versioninfo()'
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd())'
    - if [[ `uname` = "Darwin" ]]; then julia -e 'Pkg.add("Ipopt")'; fi # installs from binaries
    - julia -e 'for p in split(ENV["PKGADD"],";") Pkg.add(p) end'
    - if [ $JULIAVERSION = "julianightlies" ]; then julia test/runtests.jl; fi
    - if [ $JULIAVERSION = "juliareleases" ]; then julia --code-coverage test/runtests.jl; fi
    - julia test/hygiene.jl
    - julia test/hockschittkowski/runhs.jl
after_success:
    - if [[ $JULIAVERSION = "juliareleases" && `uname` = "Linux" ]]; then julia -e 'cd(Pkg.dir("JuMP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi


