language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - 0.7
matrix:
    allow_failures:
        - julia: 0.7
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'import Pkg; Pkg.clone(pwd())'
    - julia -e 'import Pkg; Pkg.test("JuMP", coverage=true)'
    - julia -e 'import Pkg; Pkg.add("Compat")' # needed by hygiene.jl
    - julia test/hygiene.jl
    - julia -e 'import Pkg; Pkg.add("Ipopt")' # needed for below tests
    - julia test/hockschittkowski/runhs.jl
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("JuMP")); import Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
