language: cpp
compiler:
    - gcc
notifications:
    email: false
env:
    matrix: 
        - PKGADD="Cbc;Clp" JULIAVERSION="juliareleases" 
        - PKGADD="GLPKMathProgInterface" JULIAVERSION="julianightlies" 
        - PKGADD="GLPKMathProgInterface" JULIAVERSION="juliareleases" 
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install julia -y
    - sudo apt-get install gfortran liblapack-dev
    - sudo apt-get install libgmp-dev -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'Pkg.init()'
    - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'Pkg.add("Ipopt")'; fi
    - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("JuMP"))`); Pkg.pin("JuMP"); Pkg.resolve()'
    - julia -e 'for p in split(ENV["PKGADD"],";") Pkg.add(p) end'
    - if [ $JULIAVERSION = "julianightlies" ]; then julia --code-coverage test/runtests.jl; fi
    - if [ $JULIAVERSION = "juliareleases" ]; then julia test/runtests.jl; fi
    - julia test/hygiene.jl
    - julia test/hockschittkowski/runhs.jl
after_success:
    - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'cd(Pkg.dir("JuMP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi


