environment:
  matrix:
# Releases
  - JULIAVERSION: "stable/win32"
  - JULIAVERSION: "stable/win64"
# Nightlies
#  - JULIAVERSION: "download/win32"
#  - JULIAVERSION: "download/win64"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
#  - git fetch --unshallow
  - C:\projects\julia\bin\julia-debug -e "versioninfo(); Pkg.init(); Pkg.add(\"WinRPM\"); Pkg.clone(pwd(), \"JuMP\");"

test_script:
  - C:\projects\julia\bin\julia-debug -e "Pkg.test(\"JuMP\")"
