environment:
  matrix:
  - JULIAVERSION: "x86/0.3/julia-0.3.0-prerelease-win32.exe"
# Add more lines here to test multiple Julia versions

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://s3.amazonaws.com/julialang/bin/winnt/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - git fetch --unshallow
  - C:\projects\julia\bin\julia-debug-readline -e "versioninfo(); Pkg.init(); Pkg.clone(pwd(), \"JuMP\"); Pkg.add(\"GLPKMathProgInterface\")"

test_script:
  - C:\projects\julia\bin\julia-debug-readline test\runtests.jl
